steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/example-app:latest', '.' ]
  - name: 'gcr.io/cloud-builders/docker-compose'
    args: ['build','app']
  - name: 'gcr.io/cloud-builders/docker-compose'
    args: ['run','app','rake','db:create','RAILS_ENV=test']
  - name: 'gcr.io/cloud-builders/docker-compose'
    args: ['run','app','rake','db:migrate','RAILS_ENV=test']
  - name: 'gcr.io/cloud-builders/docker-compose'
    args: ['run','app','rails','test','RAILS_ENV=test']
images: ['gcr.io/$PROJECT_ID/example-app:latest']
